

search_mode = 'fuzzy'

filter_mode = 'host'

search_mode_shell_up_key_binding = "fuzzy"

ctrl_n_shortcuts = true

db_path = "~/.history.db"

session_path = "~/.atuin-session"

dialect = "us"

auto_sync = false

update_check = false

style = "compact"

invert = false

#The initial keymap mode of the interactive Atuin search (e.g. started by the keybindings in the shells). There are four supported values: "emacs", "vim-normal", "vim-insert", and "auto". The keymap mode "emacs" is the most basic one. In the keymap mode "vim-normal", you may use k and j to navigate the history list as in Vim, whilst pressing
keymap_mode = "vim-normal"

show_preview = true

max_preview_height = 4
